name: policepatil
description: Pune Police Gramin Police-Patil App

publish_to: 'none'

version: 1.0.3

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^2.2.0
  carousel_slider: ^4.0.0
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.0
  flutter_bloc: ^7.3.0
  youtube_player_iframe: ^2.2.2
  dropdown_search: ^2.0.1

  # Network
  dio: ^4.0.0
  http: ^0.13.3
  connectivity: ^3.0.6
  url_launcher: ^6.0.18

  # Util
  intl: ^0.17.0
  geolocator: ^8.0.5
  shared_preferences: ^2.0.7
  flutter_datetime_picker: ^1.5.1 # simple date picker
  file_picker: ^4.3.3
  image_picker: ^0.8.4+2
  path: ^1.8.0

  bloc: ^7.1.0 # do not update to 8.0.0 and above or else refactor
  equatable: ^2.0.3
  meta: ^1.7.0
  package_info: ^2.0.2
  pub_semver: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.0.1+1
  flutter_lints: ^1.0.4
  flutter_launcher_icons_maker: "^0.10.1"

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:

  color: "#ffffff"
  image: assets/splash-screen.png
  color_dark: "#ffffff"
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  # command - flutter pub run flutter_native_splash:create

flutter_icons:
  android: true
  ios: true
  web: true
  image_path: "assets/police patil.png"