name: policepatil
description: Pune Police Gramin Police-Patil App

publish_to: 'none'

version: 1.0.2

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^2.2.0
  carousel_slider: ^4.0.0
  fluttertoast: ^8.0.8
  cached_network_image: ^3.2.0
  flutter_bloc: ^7.3.0
  youtube_player_iframe: ^2.2.2
  dropdown_search: ^2.0.1

  # Network
  url_launcher: ^6.0.18

  # Util
  intl: ^0.17.0
  geolocator: ^8.0.5
  flutter_datetime_picker: ^1.5.1 # simple date picker
  file_picker: ^4.3.3
  image_picker: ^0.8.4+2
  path: ^1.8.0

  # Local
  shared:
    path: '../shared'
  api:
    path: '../api'


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.0.1+1
  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:

  color: "#ffffff"
  image: assets/splash-screen.png
  color_dark: "#ffffff"
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  # command - flutter pub run flutter_native_splash:create