name: shared
description: A new Flutter package.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^7.1.0
  equatable: ^2.0.3
  meta: ^1.7.0
  intl: ^0.17.0
  package_info: ^2.0.2
  pub_semver: ^2.1.0

  api:
    path: ../api


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:

